# Generated by Django 2.1.5 on 2019-07-22 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False, verbose_name='地址id')),
                ('address_province', models.CharField(blank=True, max_length=15, null=True, verbose_name='省份')),
                ('address_city', models.CharField(blank=True, max_length=15, null=True, verbose_name='市')),
                ('address_area', models.CharField(blank=True, max_length=15, null=True, verbose_name='区/县')),
                ('address_detail', models.CharField(blank=True, max_length=100, null=True, verbose_name='详细地址')),
                ('address_tel', models.CharField(blank=True, max_length=11, null=True, verbose_name='收件人手机号')),
                ('address_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='收件人名称')),
                ('address_post_num', models.IntegerField(blank=True, null=True, verbose_name='邮编')),
                ('address_default', models.NullBooleanField(default=False, verbose_name='为true表示为默认的地址，为false表示为一般地址,默认为false')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False, verbose_name='购物车id')),
                ('cart_num', models.IntegerField(blank=True, null=True, verbose_name='加入购物车单个商品数量')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品分类id')),
                ('category_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='商品名称')),
                ('category_pid', models.IntegerField(blank=True, null=True, verbose_name='商品分类pid')),
                ('category_img', models.CharField(blank=True, max_length=255, null=True, verbose_name='列表商品主图')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品id')),
                ('goods_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='商品名称')),
                ('goods_describe', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品描述')),
                ('goods_unit', models.CharField(blank=True, max_length=60, null=True, verbose_name='单位')),
                ('goods_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价')),
                ('goods_content', models.TextField(blank=True, null=True, verbose_name='商品内容')),
                ('goods_addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='上架时间')),
                ('goods_img', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品主图')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.Category', verbose_name='类别id')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsImg',
            fields=[
                ('goodimg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品图片表id')),
                ('goodimg_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品图片表的路径')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.Goods', verbose_name='商品id')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('member_name', models.CharField(default='', max_length=100, verbose_name='用户登录名')),
                ('member_nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户昵称')),
                ('member_pwd', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户密码')),
                ('member_money', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='账户余额')),
                ('member_paypwd', models.CharField(blank=True, max_length=6, null=True, verbose_name='支付密码')),
                ('member_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='用户邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='下单表id')),
                ('order_addtime', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('order_pay_method', models.IntegerField(default=1, verbose_name='支付方式： 1:余额支付,2:微信支付,3:支付宝支付')),
                ('order_number', models.CharField(max_length=100, verbose_name='订单号')),
                ('order_status', models.IntegerField(default=1, verbose_name='订单状态： 1:未支付,2:已支付代发货,3:已发货待收货,4:已收货,5:已完成')),
                ('order_province', models.CharField(blank=True, max_length=15, null=True, verbose_name='订单省份')),
                ('order_city', models.CharField(blank=True, max_length=15, null=True, verbose_name='订单市')),
                ('order_area', models.CharField(blank=True, max_length=15, null=True, verbose_name='订单区/县')),
                ('order_detail', models.CharField(blank=True, max_length=100, null=True, verbose_name='订单详细地址')),
                ('order_tel', models.CharField(blank=True, max_length=11, null=True, verbose_name='订单收件人手机号')),
                ('order_addressee', models.CharField(blank=True, max_length=100, null=True, verbose_name='订单收件人名称')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.Address', verbose_name='地址id')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.Member', verbose_name='用户id')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单详情id')),
                ('order_detail_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='订单详情商品的名称')),
                ('order_detail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='订单详情商品的价格')),
                ('order_detail_num', models.IntegerField(blank=True, null=True, verbose_name='订单详情商品的数量')),
                ('order_detail_img', models.CharField(blank=True, max_length=255, null=True, verbose_name='订单详情商品的主图')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.Goods', verbose_name='商品id')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.Order', verbose_name='订单id')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.Goods', verbose_name='购物车id'),
        ),
        migrations.AddField(
            model_name='cart',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.Member', verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='address',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.Member', verbose_name='用户id'),
        ),
    ]
