# Generated by Django 2.1.5 on 2019-07-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_remove_category_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='列表商品主图'),
        ),
    ]
