# Generated by Django 2.1.5 on 2019-07-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_category_category_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_img',
        ),
    ]
